(() => {
const projects=window.POPPYCAT_PROJECTS||[],panels=[...document.querySelectorAll('.panel')],links=[...document.querySelectorAll('nav a')],main=document.querySelector('main');
const titles={projects:'Selected work from our team',about:'About',team:'We are...',contact:'Contact'};
const descriptions={projects:'',about:'PoppyCat Productions',team:'',contact:'Contact details coming soon.'};
const gallery=document.querySelector('.gallery'),previous=document.querySelector('#previous'),next=document.querySelector('#next'),progress=document.querySelector('#progress'),detail=document.querySelector('#project-detail');
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};
function tags(p){const n=el('div','project-tags');p.tags.forEach(t=>n.append(el('span','',t)));if(p.year)n.append(el('span','project-year',p.year));return n;}
function media(p,full=false){const box=el('div','project-art');const img=el('img');img.src=p.image;img.alt='';img.loading=full?'eager':'lazy';img.decoding='async';img.style.objectFit=full?'contain':p.fit;box.append(img);if(p.video){const v=el('video');v.dataset.src=p.video;v.muted=true;v.loop=true;v.playsInline=true;v.preload='none';v.poster=p.image;v.style.objectFit=full?'contain':p.fit;v.setAttribute('aria-hidden','true');box.append(v);}return box;}
projects.forEach(p=>{const a=el('a','project-card');a.href='#work/'+p.id;a.setAttribute('aria-label','View '+p.title);a.append(media(p));const caption=el('div','caption'),line=el('div','caption-title');line.append(el('h2','',p.title),el('span','project-arrow','↗'));caption.append(line,el('p','caption-company',p.company),tags(p),el('p','project-credit',p.person+' · '+p.role));a.append(caption);gallery.append(a);});
function play(v){if(reduced())return;if(!v.src)v.src=v.dataset.src;v.play().catch(()=>{});}
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{const v=e.target.querySelector('video');if(v){if(e.isIntersecting&&!document.hidden)play(v);else v.pause();}}),{root:gallery,threshold:.1});
gallery.querySelectorAll('.project-card').forEach(c=>observer.observe(c));
function syncGallery(){const max=gallery.scrollWidth-gallery.clientWidth;previous.disabled=gallery.scrollLeft<=1;next.disabled=gallery.scrollLeft>=max-1;const fraction=Math.min(1,gallery.clientWidth/Math.max(1,gallery.scrollWidth));progress.style.width=fraction*100+'%';progress.style.transform='translateX('+(max>0?gallery.scrollLeft/max*(1-fraction)/fraction*100:0)+'%)';}
function move(direction){const card=gallery.querySelector('.project-card');gallery.scrollBy({left:direction*((card?.offsetWidth||gallery.clientWidth*.75)+16),behavior:reduced()?'instant':'smooth'});}
previous.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));
document.addEventListener('wheel',event=>{if(event.ctrlKey||document.querySelector('#projects').hidden)return;const raw=Math.abs(event.deltaX)>Math.abs(event.deltaY)?event.deltaX:event.deltaY;const delta=raw*(event.deltaMode===1?16:event.deltaMode===2?gallery.clientWidth:1);if(!delta||gallery.scrollWidth<=gallery.clientWidth)return;event.preventDefault();gallery.scrollLeft+=delta;},{passive:false});
gallery.addEventListener('keydown',event=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();move(event.key==='ArrowRight'?1:-1);}else if(event.key==='Home'||event.key==='End'){event.preventDefault();gallery.scrollTo({left:event.key==='Home'?0:gallery.scrollWidth,behavior:reduced()?'instant':'smooth'});}});
gallery.addEventListener('scroll',syncGallery,{passive:true});
function fitInfo(){const panel=panels.find(p=>!p.hidden);if(!panel||panel.id==='projects'||panel.id==='project-detail')return;const content=panel.firstElementChild;content.style.transform='';content.style.transformOrigin='top left';const style=getComputedStyle(panel),w=panel.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight),h=panel.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom);const scale=Math.min(1,w/Math.max(1,content.scrollWidth),h/Math.max(1,content.scrollHeight));if(scale<1)content.style.transform='scale('+scale+')';}
function renderDetail(p){detail.replaceChildren();const wrapper=el('div','detail-layout');wrapper.append(media(p,true));const copy=el('div','detail-copy'),back=el('a','back-link','← All projects');back.href='#projects';copy.append(back,tags(p),el('h2','detail-title',p.title),el('p','detail-company',p.company),el('p','detail-description',p.description));const credit=el('p','detail-credit');credit.append(el('strong','',p.person),document.createTextNode(p.role));copy.append(credit);if(p.credits)copy.append(el('p','detail-other-credits',p.credits));if(p.url){const source=el('a','source-link','More about the project ↗');source.href=p.url;source.target='_blank';source.rel='noopener noreferrer';copy.append(source);}wrapper.append(copy);detail.append(wrapper);const v=detail.querySelector('video');if(v)play(v);}
function show(focus=false){const requested=location.hash.slice(1),p=requested.startsWith('work/')?projects.find(p=>p.id===requested.slice(5)):null,id=p?'project-detail':titles[requested]?requested:'projects';document.querySelectorAll('video').forEach(v=>v.pause());if(p)renderDetail(p);else detail.replaceChildren();panels.forEach(panel=>panel.hidden=panel.id!==id);const navId=p?'projects':id;links.forEach(a=>{if(a.hash==='#'+navId)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.querySelector('#page-title').textContent=titles[navId];document.querySelector('#page-description').textContent=descriptions[navId];document.querySelector('#page-description').hidden=!descriptions[navId];document.querySelector('#company-line').hidden=navId==='projects';document.querySelector('.heading-note').hidden=navId==='projects';document.title=(p?p.title:titles[id])+' | PoppyCat Productions';if(focus)main.focus({preventScroll:true});requestAnimationFrame(()=>{syncGallery();fitInfo();if(p){const v=detail.querySelector('video');if(v)play(v);}});}
show();window.addEventListener('hashchange',()=>show(true));new ResizeObserver(()=>{syncGallery();fitInfo();}).observe(main);window.addEventListener('load',fitInfo);document.fonts.ready.then(fitInfo);
document.addEventListener('visibilitychange',()=>{document.querySelectorAll('video').forEach(v=>{if(document.hidden)v.pause();else if(!v.closest('.panel').hidden){const r=v.getBoundingClientRect();if(r.right>0&&r.left<innerWidth)play(v);}});});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!detail.hidden)location.hash='projects';});
})();
